In [1]:
import rasterio
from rasterio.plot import show_hist
import matplotlib.pyplot as plt

# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\2000Edge\00N_060W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    data2000 = src.read(1)
    data2000 = data2000[data2000 != 0]
print("2000 Data processed!")

C:\Users\hyou34\AppData\Local\miniconda3\envs\py39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\hyou34\AppData\Local\miniconda3\envs\py39\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\hyou34\AppData\Local\miniconda3\envs\py39\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


2000 Data processed!


In [2]:
import rasterio
from rasterio.plot import show_hist
import matplotlib.pyplot as plt

# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\2020Edge\00N_060W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    data2020 = src.read(1)
    data2020 = data2020[data2020 != 0]
print("2020 Data processed!")

2020 Data processed!


In [8]:
import numpy as np
# 定义区间
bins = [1, 300, 600, 900, 1200]

# 统计直方图
histogram2000, bin_edges = np.histogram(data2000, bins=bins)
print(histogram2000)

histogram2020, bin_edges = np.histogram(data2020, bins=bins)
print(histogram2020)

[16997482  9244465  2280380   638518]
[20354559 11683650  2467167   626438]


In [11]:
# 每个像素的边长（单位：米）
pixel_length = 25

# 计算每个像素的面积（单位：平方米）
pixel_area = pixel_length ** 2

# 每个区间的像素数量
pixel_counts_2000 = [16997482, 9244465, 2280380, 638518]
pixel_counts_2020 = [20354559, 11683650, 2467167, 626438]
Diff = (pixel_counts_2000-pixel_counts_2020)/pixel_counts_2000

# 计算每个区间的总面积（单位：平方米）
total_area_2000 = sum(pixel_counts_2000) * pixel_area
total_area_2020 = sum(pixel_counts_2020) * pixel_area

# 计算面积的变化
area_change = total_area_2020 - total_area_2000

# 打印结果
print("2000年森林边缘总面积：", total_area_2000, "平方米")
print("2020年森林边缘总面积：", total_area_2020, "平方米")
print("20年间森林边缘面积变化：", area_change, "平方米")


# 边长区间（单位：米）
edge_lengths = [25, 50, 75, 100]

# 计算每个区间的总长度（单位：米）
total_lengths_2000 = sum(data2000)
total_lengths_2020 = sum(data2020)

# 打印结果
print("2000年森林边缘总长度：", total_lengths_2000, "米")
print("2020年森林边缘总长度：", total_lengths_2020, "米")


2000年森林边缘总面积： 18225528125 平方米
2020年森林边缘总面积： 21957383750 平方米
20年间森林边缘面积变化： 3731855625 平方米
2000年森林边缘总长度： 1122040600 米
2020年森林边缘总长度： 1340727800 米
森林边缘长度变化百分比： 19.490132531746177 %
森林边缘面积变化百分比： 20.475980720037434 %


In [16]:
import numpy as np

# 计算像素数量的相对差异
diff = 100*(np.array(pixel_counts_2020) - np.array(pixel_counts_2000)) / np.array(pixel_counts_2000)

# 打印结果
print("像素数量的相对差异：", diff)


像素数量的相对差异： [19.75043715 26.38535599  8.19104711 -1.89188089]


In [12]:
import rasterio
from rasterio.plot import show_hist
import matplotlib.pyplot as plt

# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\2000Edge\00N_050W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    data2000_00N_050W = src.read(1)
    data2000_00N_050W = data2000_00N_050W[data2000_00N_050W != 0]
print("2000 Data processed!")
# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\2020Edge\00N_050W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    data2020_00N_050W = src.read(1)
    data2020_00N_050W = data2020_00N_050W[data2020_00N_050W != 0]
print("2020 Data processed!")

2000 Data processed!
2020 Data processed!


In [13]:
import numpy as np
# 定义区间
bins = [1, 300, 600, 900, 1200]

# 统计直方图
histogram2000_00N_050W, bin_edges = np.histogram(data2000_00N_050W, bins=bins)
print(histogram2000_00N_050W)

histogram2020_00N_050W, bin_edges = np.histogram(data2020_00N_050W, bins=bins)
print(histogram2020_00N_050W)

[57208288 35160889 11700784  3771820]
[48961256 30829207  9033571  2679809]


In [18]:
diff = 100*(np.array(histogram2020_00N_050W) - np.array(histogram2000_00N_050W)) / np.array(histogram2000_00N_050W)
diff

array([-14.41579933, -12.31960318, -22.79516484, -28.95183227])

In [22]:
Total_edge_2020 = np.sum(data2020)*0.1*0.001
Total_edge_2000 = np.sum(data2000)*0.1*0.001

print("Total_edge_2020", Total_edge_2020)
print("Total_edge_2000", Total_edge_2000)

Total_edge_2020 201307.5374
Total_edge_2000 388170.4463


In [30]:
# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\new_001_di\00N_050W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    di_data = src.read(1)
    di_data = di_data[di_data != 0]
print("di Data processed!")

# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\new_001_dd\00N_050W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    dd_data = src.read(1)
    dd_data = dd_data[dd_data != 0]
print("dd Data processed!")

# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\new_001_ii\00N_050W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    ii_data = src.read(1)
    ii_data = ii_data[ii_data != 0]
print("ii Data processed!")

# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\new_001_id\00N_050W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    id_data = src.read(1)
    id_data = id_data[id_data != 0]
print("id Data processed!")

# 打开.tif文件
file_path = r'G:\Hangkai\Global forest edge\new_001_stable\00N_050W.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    stable_data = src.read(1)
    stable_data = stable_data[stable_data != 0]
print("stable Data processed!")

di Data processed!
dd Data processed!
ii Data processed!
id Data processed!
stable Data processed!


In [31]:
ID_edge = np.nansum(id_data)
II_edge = np.nansum(ii_data)
DD_edge = np.nansum(dd_data)
DI_edge = np.nansum(di_data)
Stable_edge = np.nansum(stable_data)

print("Total_edge_2020", Total_edge_2020)
print("Total_edge_2000", Total_edge_2000)
print("ID_edge", ID_edge)
print("II_edge", II_edge)
print("DD_edge", DD_edge)
print("DI_edge", DI_edge)
print("Stable_edge", Stable_edge)

Total_edge_2020 201307.5374
Total_edge_2000 388170.4463
ID_edge 570527.7
II_edge 155319.05
DD_edge 1179776.6
DI_edge 358719.78
Stable_edge 3394000.8


In [32]:
# 打开.tif文件
file_path = r'G:\Hangkai\CONUS Forest Edge Mapping\Forest_Depth_Classification\2017LC.tif'

# 读取.tif文件中的数据
with rasterio.open(file_path) as src:
    DATA2017 = src.read(1)
    DATA2017 = DATA2017[DATA2017 != 0]
print("DATA2017 processed!")

DATA2017 processed!
